import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import Mylibrary from "@/Components/MyLibrary/MyLibrary";
import { MusicPlayerProvider } from "@/ContextApi/playContext";
import { UserProvider } from "@/ContextApi/userContext";
import { LanguagePopup } from "@/Components/LanguagePage/Language";
import { PolicyPopup } from "@/Components/TermsandPrivacy/PrivacyPolicy";
import { TermsPopup } from "@/Components/TermsandPrivacy/Terms";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <MusicPlayerProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <PolicyPopup />
            <LanguagePopup />

            <TermsPopup />

            <div className="h-full w-full fixed m-0 p-0">
              <NavBar />
              <div className="flex bg-black  relative max-h-[89vh]">
                <Mylibrary />

                {children}
              </div>

              <Footer />
            </div>
          </body>
        </html>
      </MusicPlayerProvider>
    </UserProvider>
  );
}
